### ISSUE TITLE
Exception when cancelling slurm jobs

### ISSUE THREAD

**Issue by lmoureaux** [riga/law#116]
I get an exception in `law` when using the `--cancel-jobs` option with `slurm`:
```
Traceback (most recent call last):
  File "/afs/desy.de/user/r/riegerma/public/law_sw/luigi/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/afs/desy.de/user/r/riegerma/public/law_sw/luigi/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/afs/desy.de/user/r/riegerma/public/law_sw/law/law/workflow/remote.py", line 448, in run
    self.cancel()
  File "/afs/desy.de/user/r/riegerma/public/law_sw/law/law/workflow/remote.py", line 529, in cancel
    len(errors), len(job_ids), task.task_id))
TypeError: object of type 'filter' has no len()
```

**Comment by riga** [comment]
Thanks for reporting @lmoureaux ! 🎉

Did you also check if this happens on master? Also, which python version are you using?
