### ISSUE TITLE
Unicode error with Condor and @log decorator

### ISSUE THREAD

**Issue by ast0815** [riga/law#65]
Hello,

I am again having problems with the @log operator and unicode. At least that is what the error message tells me. The weird thing is, that this time the error only pops up when the task is run as a condor job. Maybe stdout and stderr are weird in the Condor environment?

This is enough to cause the error:

```
class Bug(law.Task):
    default_log_file = '/path/to/log/file'
    def run(self):
        print_("ABC")
        print_("XYZ")
    def output(self):
        return []
    def requires(self):
        return []
```

When I run this task in a regular shell environment it works without flaws. If I run it in a condor job (i.e. the condor job runs a shell script in which `law run Bug` is executed) I get an exception:

```
Traceback (most recent call last):
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 92, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 126, in log
    traceback.print_exc(file=tee)
  File "/usr/lib64/python2.7/traceback.py", line 232, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/lib64/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/lib64/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 836, in write
    self._write(*args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 899, in _write
    consumer.write(*args, **kwargs)
TypeError: must be unicode, not str
```

**Comment by ast0815** [comment]
Thank you! As an additional pointer, commenting out lines 121 and 122 in law/decorator.py seems to fix the exception, but of course there is no logging then:

```
            #sys.stdout = tee
            #sys.stderr = tee
```

**Comment by riga** [comment]
Hi @ast0815 ,

I struggle to reproduce the error you observe.
Probably there is some problem in the configuration of your cluster's condor setup?

Do you forward all environment variables to your remote jobs, à la https://github.com/riga/law/blob/master/examples/htcondor_at_cern/analysis/framework.py#L72 ?

I created a minimal example and ran it successfully on 3 different clusters (python 2.7, 3.5, 3.6). You can grab it [here](https://transfer.sh/H87OQ/law_test.tgz) and run it via

```shell
source setup.sh
law db
law run CondorBug --local-scheduler --poll-interval 0.2 --retries 0 --transfer-logs
```

Does that work for you?

**Comment by ast0815** [comment]
As I said, I am not currently using the CondorWorkflow functionality. I am simply sending out condor jobs (using a `condor.job` file and `condor_submit`) that run `law run Bug`.  Could you give that a try? I will also try yo implement the proper CondorWorkflow on my end.

**Comment by riga** [comment]
Ok, could you post your `condor.job` file? That would make debugging way easier.

**Comment by ast0815** [comment]
Sure. Here is my `condor.job`:
```
executable = condor_script.sh
universe = vanilla
requirements = OpSysAndVer == "CentOS7"
error = condor.err
output = condor.out
#error = /dev/null
#output = /dev/null
log = condor.log

transfer_input_files = condor_script.sh,law.cfg
transfer_output_files =

queue 1
```

And here is my `condor_script.sh`:
```
#!/bin/bash
. /opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/cluster_setup.sh
law db
law run Bug
```

**Comment by ast0815** [comment]
Also, is there maybe some more documentation about the CondorWorkflow somewhere? Aside from just the examples? I cannot get it to work at all right now. Even when not doing any logging.

**Comment by riga** [comment]
My job file looks identical, except for a `getenv = true`. Is there another python 2.7.x version on the worker node?

> Also, is there maybe some more documentation about the CondorWorkflow somewhere?

Right now, only for generic workflows: https://law.readthedocs.io/en/latest/workflows.html

Docs on the remote workflows will come soon, but e.g. the htcondor_at_vispa/cern examples basically explain the most important parts.
